sonar.projectKey=frontend-angular
sonar.projectName=frontend-angular
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/frontend-angular/lcov.info

# Ignore false positives and hardcoded variables used in development
sonar.issue.ignore.multicriteria=e1,e2

# Ignore hardcoded URL in config
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S1075
sonar.issue.ignore.multicriteria.e1.resourceKey=src/app/core/utils/config.ts

# Ignore hardcoded secrets / URLs in environments
sonar.issue.ignore.multicriteria.e2.ruleKey=*
sonar.issue.ignore.multicriteria.e2.resourceKey=src/environments/*.ts
